// SPDX-License-Identifier: LicenseRef-OpenLBM-Commons-1.0
// SPDX-FileCopyrightText: 2026 FutureBuild, Inc. and OpenLBM contributors

package governance

import (
	"encoding/json"
	"strings"

	"github.com/gablelbm/gable/internal/platform/httpx"
	"github.com/google/uuid"
)

// CreateRFCInput is the body of POST /api/v1/governance/rfcs. The content is
// generated by the provider at create, never sent by the client; status is
// the lifecycle's first value, never sent either (a request carrying either
// is a 400 naming it).
type CreateRFCInput struct {
	Title            *string         `json:"title"`
	ProblemStatement *string         `json:"problem_statement"`
	ProposedSolution *string         `json:"proposed_solution"`
	AuthorID         *string         `json:"author_id"`
	Content          json.RawMessage `json:"content"`
	Status           json.RawMessage `json:"status"`
	Revision         json.RawMessage `json:"revision"`
}

// ParsedCreate is the validated create.
type ParsedCreate struct {
	Title            string
	ProblemStatement string
	ProposedSolution string
	AuthorID         *uuid.UUID
}

// Parse validates the create, collecting every problem into one 400.
func (r *CreateRFCInput) Parse() (*ParsedCreate, error) {
	v := &httpx.Validator{}
	out := &ParsedCreate{}
	if r.Title == nil || strings.TrimSpace(*r.Title) == "" {
		v.Check(false, "title", "is required")
	} else {
		t := strings.TrimSpace(*r.Title)
		v.Check(len(t) <= 255, "title", "must be 255 characters or fewer")
		out.Title = t
	}
	if r.ProblemStatement == nil || strings.TrimSpace(*r.ProblemStatement) == "" {
		v.Check(false, "problem_statement", "is required")
	} else {
		p := strings.TrimSpace(*r.ProblemStatement)
		v.Check(len(p) <= 10000, "problem_statement", "must be 10000 characters or fewer")
		out.ProblemStatement = p
	}
	if r.ProposedSolution == nil || strings.TrimSpace(*r.ProposedSolution) == "" {
		v.Check(false, "proposed_solution", "is required")
	} else {
		p := strings.TrimSpace(*r.ProposedSolution)
		v.Check(len(p) <= 10000, "proposed_solution", "must be 10000 characters or fewer")
		out.ProposedSolution = p
	}
	if r.AuthorID != nil && strings.TrimSpace(*r.AuthorID) != "" {
		if id, ok := v.UUID("author_id", r.AuthorID, true); ok {
			out.AuthorID = &id
		}
	}
	for field, raw := range map[string]json.RawMessage{
		"content": r.Content, "status": r.Status, "revision": r.Revision,
	} {
		if len(raw) > 0 && string(raw) != "null" {
			v.Check(false, field, "is not accepted on a create")
		}
	}
	if err := v.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateRFCInput is the body of PUT /api/v1/governance/rfcs/{id}. Every
// editable field is a pointer: nil leaves it alone. Status moves through the
// transitions route; author_id is set once at create; both are refused here.
type UpdateRFCInput struct {
	Title            *string         `json:"title"`
	ProblemStatement *string         `json:"problem_statement"`
	ProposedSolution *string         `json:"proposed_solution"`
	Content          *string         `json:"content"`
	Status           json.RawMessage `json:"status"`
	AuthorID         json.RawMessage `json:"author_id"`
	Revision         json.RawMessage `json:"revision"`
}

// ParsedUpdate is the validated update.
type ParsedUpdate struct {
	Title            *string
	ProblemStatement *string
	ProposedSolution *string
	Content          *string
}

// Parse validates the update and reads the body's revision.
func (r *UpdateRFCInput) Parse() (*ParsedUpdate, *int64, error) {
	v := &httpx.Validator{}
	out := &ParsedUpdate{}
	if r.Title != nil {
		t := strings.TrimSpace(*r.Title)
		if t == "" {
			v.Check(false, "title", "cannot be emptied")
		} else {
			v.Check(len(t) <= 255, "title", "must be 255 characters or fewer")
			out.Title = &t
		}
	}
	for field, ptr := range map[string]*string{
		"problem_statement": r.ProblemStatement, "proposed_solution": r.ProposedSolution,
	} {
		if ptr == nil {
			continue
		}
		p := strings.TrimSpace(*ptr)
		if p == "" {
			v.Check(false, field, "cannot be emptied")
			continue
		}
		v.Check(len(p) <= 10000, field, "must be 10000 characters or fewer")
		if field == "problem_statement" {
			out.ProblemStatement = &p
		} else {
			out.ProposedSolution = &p
		}
	}
	if r.Content != nil {
		c := strings.TrimSpace(*r.Content)
		v.Check(len(c) <= 100000, "content", "must be 100000 characters or fewer")
		out.Content = &c
	}
	for field, raw := range map[string]json.RawMessage{
		"status": r.Status, "author_id": r.AuthorID,
	} {
		if len(raw) > 0 && string(raw) != "null" {
			v.Check(false, field, "is not accepted on an update"+statusHint(field))
		}
	}
	var revision *int64
	if n, ok := v.Int("revision", r.Revision, false); ok {
		v.Check(n >= 1, "revision", "must be a revision number, 1 or more")
		revision = &n
	}
	if err := v.Err(); err != nil {
		return nil, nil, err
	}
	return out, revision, nil
}

func statusHint(field string) string {
	if field == "status" {
		return " (use POST /api/v1/governance/rfcs/{id}/transitions)"
	}
	return ""
}
